[package]
name = "well-being"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.0.32", features = ["derive"] }
regex = "1.7.0"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.91"
tempfile = "3.3"

[[bin]]
name = "extract"
path = "src/extract/main.rs"
